-- Write SQL queries to perform the following tasks using the Sakila database:

-- List the number of films per category.

SELECT *
FROM sakila.film_category as a
LEFT JOIN sakila.film as b
ON a.film_id = b.film_id
ORDER BY category_id;

-- Retrieve the store ID, city, and country for each store.
SELECT *
FROM sakila.address as a
LEFT JOIN sakila.store as b
ON a.address_id = b.address_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT store_id, sum(amount) as total_revenue
FROM sakila.staff as a
LEFT JOIN sakila.payment as b
ON a.staff_id = b.staff_id
GROUP BY store_id;

-- Determine the average running time of films for each category.

SELECT category_id, round(sum(length/60), 2)
FROM sakila.film as a
LEFT JOIN sakila.film_category as b
ON a.film_id = b.film_id
GROUP BY category_id;